# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
