# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20160711_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
